name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-agent:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
#          macos-latest, 
          windows-latest
        ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          app/package-lock.json
    - name: Restore Agent NPM dependencies
      run: |
        npm ci
        npm ci --prefix app

    - name: make
      run: npm run make
