name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-agent:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Restore Agent NPM dependencies
      run: npm ci

    - name: make
      run: npm run make
